### ISSUE TITLE
Websocket error cases

### ISSUE THREAD

**Issue by khuezy** [harry-sm/BittrexRx#1]
Hi,
First of all, thanks for creating this project. It looks well architected and well written.

Have you encountered an issues w/ a 503 response from bittrex? It has something to do w/ cloudflare or bittrex service not being available.

Does this library handle those cases?

If not, can I add some feature requests and/or contribute?

Thanks!

**Comment by harry-sm** [comment]
Hello,
Thank you for taking an interest in this project!

I personally have not encountered the 503 issue and I was unaware that there was an issue with cloudflare.

Please feel free to contribute.
Thanks!

**Comment by harry-sm** [comment]
@khuezy 
Could you check if you're still experiencing the 503 error I pushed an update.

Thanks.

**Comment by khuezy** [comment]
@harry-sm 
I have not switched to using this library yet.
I'd like to switch over in a couple months once I've stabilized my bot.

I've made the mistake of hitting the bittrex api 100's of request/second, which caused me to be cloudflared. 

Bittrex states somewhere online (it's not really documented on their API sheet) that you should only hit each `/api/resource` at most 1/min. If you go over that, you risk being rate limited.

If you ever get `resource unavailable` or `503`, it'll throw one of several `signalr` `serviceHandlers` errors (`onerror`, etc...). Just hook the `disconnected` handler and resubscribe to the markets to reconnect to the socket.

So a question for you:
Should the library handle this disconnect? Or should the application be responsible for it?

**Comment by harry-sm** [comment]
@khuezy 
Currently the implementation of the  signalr client doesn't require me to explicitly call the start function (`this.wsclient.start()` see socket-client.ts line 22) to connect to bittrex, hence the `serviceHandlers` are not active. I avoid calling this method to avoid the connection failed error as the client is still able to connect to the sever and receive data. 

I have seen [node.bittrex.api](https://github.com/dparlevliet/node.bittrex.api) cloudflare solution but when I to connect to the socket server using this library I receive not data, so I took a different approach where I get the data but no `serviceHandlers` functionality.

If there is another solution I am open to it. Then the library could handle reconnecting to the server.

**Comment by khuezy** [comment]
@harry-sm 
Interesting! Please let me know if you're able to continuously receive socket data w/o any interruptions.

**Comment by harry-sm** [comment]
@khuezy 
Sometimes I get an empty object but I filter that out so the end user wont see that.

**Comment by harry-sm** [comment]
@khuezy 
My first test I received socket data for about 5 hrs.
The second test I had someone else log the data and they got around 8 hrs.

For simplicity sake I logged the Nounce and a timestamp.

Nounce: 21361 TimeStamp: 2017-11-28 00:54:53
Nounce: 21362 TimeStamp: 2017-11-28 00:55:06
Nounce: 21363 TimeStamp: 2017-11-28 00:55:18
Nounce: 21364 TimeStamp: 2017-11-28 00:55:31
.....
Nounce: 23633 TimeStamp: 2017-11-28 08:55:58
Nounce: 23634 TimeStamp: 2017-11-28 08:56:11
Nounce: 23635 TimeStamp: 2017-11-28 08:56:24
Nounce: 23636 TimeStamp: 2017-11-28 08:56:37
Nounce: 23637 TimeStamp: 2017-11-28 08:56:50

![image](https://user-images.githubusercontent.com/15040197/33354315-3f9a4b6a-d480-11e7-960a-c89a4da17dec.png)

**Comment by khuezy** [comment]
@harry-sm 
Thanks for doing that!

Is the `Connection aborted` a manual abort?

Did the socket disconnect after 5 and 8 hours? Or was that just the duration of the test.

**Comment by harry-sm** [comment]
@khuezy 
The `Connection aborted` was from the server.
Yes, the socket disconnected after 5 and 8 hours, the test duration was for 24 hours.

**Comment by khuezy** [comment]
The way that I've resolved on node.bittrex.api this was just handle `serviceHandlers.disconnected` and just refire the function that subscribed to the `['BTC-PAIRS...']`. This allows me to seamlessly record all the candles and book orders continuously.

I believe all errors will end up triggering the `disconnected` event.

**Comment by harry-sm** [comment]
@khuezy 

Here is the log file
[debug.log](https://github.com/harry-sm/BittrexRx/files/1512582/debug.log)

**Comment by harry-sm** [comment]
@khuezy 

My current solution to getting data from the sockets disables the `serviceHandlers`, that is its down fall.

When I start the socket client `this.wsclient.start()`  I get the following:

`Error: Sec-WebSocket-Accept header from server didn't match expected value of PbtbECK+MGymuVFxvAI46aYpivQ= `

**Comment by khuezy** [comment]
@harry-sm 

Are you trying to `start()` after the disconnect?

I've encountered that error before when trying to `start()` without properly `end()`ing the socket. The WebSocket-Accept header needs to be resynced w/ the server.

**Comment by harry-sm** [comment]
@khuezy 

I'm trying to start upon instantiation.

**Comment by khuezy** [comment]
@harry-sm 

Did you set the cookie headers prior to starting?

```
this.wsclient.headers['User-Agent'] = response.request.headers.user_agent;
this.wsclient.headers.cookie = response.request.headers.cookie;
this.wsclient.start()
```

**Comment by harry-sm** [comment]
@khuezy 

I'll look into that. Thanks

**Comment by harry-sm** [comment]
@khuezy 

I have added cloudflare cookie to both the http and socket requests.
We should see some improvements in connection stability.

**Comment by harry-sm** [comment]
@khuezy 

I implemented your auto reconnect code, during the test I got the following:

```
Scheduled Reconnection: Error: read ECONNRESET
Reconnecting...
Websocket auto reconnecting.
Error Message:  HTTP Negotiate Error
Exception:  { Error: getaddrinfo ENOENT socket.bittrex.com:443
    at Object._errnoException (util.js:1024:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'getaddrinfo',
  hostname: 'socket.bittrex.com',
  host: 'socket.bittrex.com',
  port: 443 }
```
Any insight into whats happening ?

Full log
[log.txt](https://github.com/harry-sm/BittrexRx/files/1533826/log.txt)

**Comment by harry-sm** [comment]
@khuezy 

I made some minor changes and got a auto reconnect, but I'm not sure if all the cases that causes a disconnection are covered.

[log.txt](https://github.com/harry-sm/BittrexRx/files/1537668/log.txt)

**Comment by khuezy** [comment]
@harry-sm 

Sorry, been busy last few days w/ the cryptomarket.

I've seen that error before but don't recall exactly where. I think it's an occasional expected error that can be ignored and retry.

**Comment by harry-sm** [comment]
@khuezy 

I'm holding bags so I stopped watching the market.
To handle all disconnected errors I'm doing a force restart. Hopefully that handles it.
